#ifndef UDP_TEST_CONFIG_H
#define UDP_TEST_CONFIG_H

#define UDP_TEST_IP_ADDR0 192U
#define UDP_TEST_IP_ADDR1 168U
#define UDP_TEST_IP_ADDR2 1U
#define UDP_TEST_IP_ADDR3 10U
#define UDP_TEST_NETMASK_ADDR0 255U
#define UDP_TEST_NETMASK_ADDR1 255U
#define UDP_TEST_NETMASK_ADDR2 255U
#define UDP_TEST_NETMASK_ADDR3 0U
#define UDP_TEST_GATEWAY_ADDR0 192U
#define UDP_TEST_GATEWAY_ADDR1 168U
#define UDP_TEST_GATEWAY_ADDR2 1U
#define UDP_TEST_GATEWAY_ADDR3 1U

#define UDP_TEST_PORT 20001U
#define UDP_TEST_MAX_PAYLOAD 512U

#endif
