#ifndef ROBSTRIDE_TEST_CONFIG_H
#define ROBSTRIDE_TEST_CONFIG_H

#define ROBSTRIDE_TEST_CAN_BUS 1U
#define ROBSTRIDE_TEST_MASTER_ID 0xFDU
#define ROBSTRIDE_TEST_MOTOR_ID 15U

/* RS00=0, RS01=1, RS02=2, RS03=3, RS04=4, RS05=5, RS06=6. */
#define ROBSTRIDE_TEST_MODEL 0U
#define ROBSTRIDE_TEST_DIAGNOSTIC_PERIOD_MS 200U

/* Keep at 0 until diagnostics and the independent emergency stop are proven. */
#ifndef ROBSTRIDE_TEST_ENABLE_MOTION
#define ROBSTRIDE_TEST_ENABLE_MOTION 0
#endif

/* Used only when ROBSTRIDE_TEST_ENABLE_MOTION is 1. */
#define ROBSTRIDE_TEST_ROTATION_RAD 0.50F
#define ROBSTRIDE_TEST_PROFILE_SPEED_RAD_S 0.50F
#define ROBSTRIDE_TEST_POSITION_TOLERANCE_RAD 0.05F
#define ROBSTRIDE_TEST_MOTION_TIMEOUT_MS 5000U
#define ROBSTRIDE_TEST_COMMAND_STEP_MS 50U
#define ROBSTRIDE_TEST_ENABLE_SETTLE_MS 200U
#define ROBSTRIDE_TEST_POSITION_SETTLE_MS 200U

#endif
